import "@/app/globals.css";
import { Providers } from "./providers";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-gray-800` }>
                <Providers>
                    <div className="w-screen h-screen flex justify-center items-center">
                        <div className="flex flex-col gap-5 min-h-fit max-h-screen bg-white dark:bg-gray-600 h-4/5 w-[700px] max-w-full p-5 rounded-xl shadow-md dark:shadow-gray-900 justify-center place-items-center">
                        {children}
                        </div>
                    </div>
                </Providers>

            </body>
        </html>
    );
}
